# Changes here will be overwritten by Copier
_commit: 5.0.0a4-1-gef13f42
_src_path: ../python-copier-template
author_email: ''
author_name: ''
description: ''
distribution_name: repo-with-renovate
docker: true
docker_debug: false
docs_type: sphinx
git_platform: github.com
github_org: test-renovate-dls
package_name: repo_with_renovate
pypi: true
repo_name: repo-with-renovate
strict_typing: true
type_checker: pyright
